version: '3.8'
services:
  frontend:
    build: ./frontend/
    container_name: frontend
    ports: 
      - "3000:3000"
  database: 
    image: mysql:8
    restart: always
    tty: true
    volumes:
      - "./database/dump/:/docker-entrypoint-initdb.d/"
    env_file:
      - .env
    ports: 
      - "6603:3306"
    command: mysqld
  backend: 
    build: ./server/
    container_name: backend
    restart: always
    tty: true
    env_file:
      - .env
    environment:
      - IS_BUILD=true
    command: php -S 0.0.0.0:8080 /server/router.php
    ports: 
      - "8080:8080"
    depends_on:
      - database